### ISSUE TITLE
Get more device information

### ISSUE THREAD

**Issue by titilambert** [TheMicDiet/chihiros-led-control#17]
In the Chihiros app, we have more device information.
* Product
* Type
* Device ID (which is the name)
* Serial Number
* Production Date
* Dealer
* Dealer Location
* Firmware version

Is it possible to get at least the `Firmware version` ? It could be a nice addition for the HA integration.

Thank !

**Comment by TheMicDiet** [comment]
I think it must be possible to get the firmware version, but I haven't found a way to read data from the device.
