### ISSUE TITLE
Feature: Home Assistant Integration

### ISSUE THREAD

**Issue by TheMicDiet** [TheMicDiet/chihiros-led-control#2]
https://developers.home-assistant.io/docs/creating_component_index

**Comment by titilambert** [comment]
Hello !
Thanks for your work !
I have 2 chihiros eggs and your tool is working ! (even if it has only 2 ilghts (red and green)
I can probably help on the home assistant integration.
I have few questions for you
* how do you want to do it ?
  * as official integration, in the home assistant core source code ?
  * as a third part integration, usable with hacs ?
    * In this case, where do you want to put the code of this integration ?
      * in this repo ?
      * in another repo ?
      
Thanks again !

**Comment by TheMicDiet** [comment]
Hi, I think we can add it in this repo as a third party integration with hacs

**Comment by kingunlim** [comment]
i cant wait for the addon in home assistant

**Comment by titilambert** [comment]
Hello ! 
I have an alpha first version of a custom integration which is working with my 2 tiny terrarium eggs !
![image](https://github.com/TheMicDiet/chihiros-led-control/assets/47721/4a67bf84-5e28-41fa-b4eb-d78e8b287021)
![image](https://github.com/TheMicDiet/chihiros-led-control/assets/47721/da288f4b-c4bd-4444-bd68-2a9f7fa4aae4)

@TheMicDiet Do you want to create a new repo ? Then I could push my code there to let people testing it. Once you did it, let me know, I will do a PR to add Chihiros icon/logo to the home assistant brands repo.  

For now, I have some doubts how the code will act with other Chihiros lights...

Also, do you know if the Chihiros lights are only RGB (and RB for tiny terrarium eggs) ? or there are some models RGBW/RGBWW ?

Thanks !

**Comment by TheMicDiet** [comment]
Hi @titilambert, afaik, there are lights that are RGB, RGBW as well as single color (white) only.

**Comment by titilambert** [comment]
@TheMicDiet @kingunlim I need your opinion:
I have 2 tiny terrarium eggs which are exposing ONLY red and green. So this is only `RG` of the `RGB`.
Should I create an RGB light entity in HA or two BRIGHTNESS lights (one for `red`, the other for `green`) ?
And I have the same question for any other Chihiros lights. I mean, for this kind of light, we do not care about the colour of the light, but we want to control each colour individual light (one `red`, one `green`, one `blue`, maybe one or two `white`)?
Thanks for your answers.

**Comment by TheMicDiet** [comment]
Hi @titilambert, I have no RGB light so it doesn't really matter to me. However, if you ask me, it would make sense to have separate controls for each color, as long as it doesn't get too complicated. Feel free to implement as you prefer it.

**Comment by kingunlim** [comment]
> @TheMicDiet @kingunlim I need your opinion:
> 
> I have 2 tiny terrarium eggs which are exposing ONLY `red` and `green`. So this is only `RG` of the `RGB`.
> 
> Should I create an RGB light entity in HA or two BRIGHTNESS lights (one for `red`, the other for `green`) ?
> 
> And I have the same question for any other Chihiros lights. I mean, for this kind of light, we do not care about the colour of the light, but we want to control each colour individually (one `red`, one `green`, one `blue`, maybe one or two `white`)?
> 
> Thanks for your answers.

so i have a chihiros wrgb2 so individual controlls would be very nice.
but im not entirely sure what can be possible?
in the app there are scenes and so on, but when i can activate the light and the last set light in the app is loaded that would be great enough, i thing a gradual shift is hard to make? so i mean when home assistant turn on the light maybe the light slowly turns to a specific percentage. (but as i write i think a automation can do this also?) thank you guys for your work!

**Comment by titilambert** [comment]
Ok ! So I will do one monochrome light entity per colour. It will not be more difficult !

**Comment by kingunlim** [comment]
@titilambert 
awesome, im curious, can i already add the addon in home assistant via hacks?

**Comment by titilambert** [comment]
Not yet, we have to make te repo hacs compatible. I never did that since I'm using hacs...

**Comment by kingunlim** [comment]
alright i asume you mean you dont use hacs? 
so then i will wait for an option to install it via homeassistant via an install option.
can you please write again if there is a option to install? best regards and thx again

**Comment by titilambert** [comment]
Sorry, I confirm I do not use hacs.
To help you I need to know more about your HA installation. Can you give me more details ?
Or if you can wait few more days I should be able to make it hacs compatible.

**Comment by kingunlim** [comment]
of corse no problem i can wait till you are ready 👍

**Comment by titilambert** [comment]
Hello ! my fork/branch is ready for a first HACS test: https://github.com/titilambert/chihiros-led-control/tree/ha_integration
I do not know how you can put a git repo URL and branch in HACS, but here is the info I can give:
* repo url: `https://github.com/titilambert/chihiros-led-control.git`
* branch (or release): `ha_integration`

Let me know if you have any questions/issues/comments !

Note: this will change when it will be merged to this repo

**Comment by kingunlim** [comment]
i dont know but i think something is wrong ![image](https://github.com/TheMicDiet/chihiros-led-control/assets/42124176/e13958bc-f48e-4545-8a3e-779875cda8de)

**Comment by kingunlim** [comment]
maybe this is the problem? https://github.com/hacs/integration/issues/2754

**Comment by kingunlim** [comment]
![image](https://github.com/TheMicDiet/chihiros-led-control/assets/42124176/8000c8ce-9d36-479e-babf-ad06c5dc1eea)

**Comment by titilambert** [comment]
@kingunlim did you had a chance to select the `ha_integratoin` branch ?
If not, this error is completely normal.
Let me know, and I will do something to get my main branch working

**Comment by kingunlim** [comment]
im sry i dont know how i coild do that?
normaly i go in hacs and select user repository and the i insert the url an choose the category like this:
![image](https://github.com/TheMicDiet/chihiros-led-control/assets/42124176/0d0589bd-0f3e-49f5-aabc-89b4ed69d73d)

**Comment by titilambert** [comment]
@kingunlim can you retry ? I just merged on my main branch. Just try with:
* repo url: https://github.com/titilambert/chihiros-led-control.git
* branch: main

**Comment by kingunlim** [comment]
yes, now its working ;)
![image](https://github.com/TheMicDiet/chihiros-led-control/assets/42124176/2f4766c3-601d-4461-8abe-8bcc7cce10da)

so, now i must learn to make the right actions to turn the lights on and off, 
when im in the app i can akticate the light and then i goes for example 70 white 70 red and 70 blue, now in your integration i must activate all channels manually?
or do you plan to update the integration for better communication with for example the wrgb2?
best regards!

**Comment by titilambert** [comment]
Hello! First thanks for testing it ! I'm happy it is now working for you.
In fact, the app keeps some “profiles” about each color, like a shortcut.
I don't think I can do that in the integration since it will be different for each user.
So I would recommend creating a group of light, see https://www.home-assistant.io/integrations/group/#binary-sensor-light-and-switch-groups.
With that, I guess you will have the behavior you want to turn on/off the light quickly.
