### ISSUE TITLE
Support for chihrios C-RGB

### ISSUE THREAD

**Issue by daaex1** [TheMicDiet/chihiros-led-control#32]
Hy 

Cant add chihrios c-rgb. Is it possible to integrate

**Comment by TheMicDiet** [comment]
HI @daaex1, probably, yes.  If you provide me the name of your device, I can add it and you can try if it works.

**Comment by daaex1** [comment]
Thank you. I only have the folloeing : CII RGB

Can't find any other description.

**Comment by TheMicDiet** [comment]
I need the name from the device settings in the chihiros app e.g. DYNA2XXXXXXXXXXXX

**Comment by daaex1** [comment]
Hy

Sorry, got it.

DYNCRGPC14FE8XXXXXX

**Comment by TheMicDiet** [comment]
Hi @daaex1, you can try out version 0.3.0.

**Comment by daaex1** [comment]
Yes it works! Thank you very much.
