### ISSUE TITLE
Unable to add WRGB 2 10th edition 

### ISSUE THREAD

**Issue by HannibalChau** [TheMicDiet/chihiros-led-control#38]
Hello,

I'm having an issue adding WRGB 2 10th edition.  Would you be able to add it?  Device id: DYNW12PD9EC8584B299

Thanks

**Comment by senna1992** [comment]
I did connect with the standard wrgb ii successfully

 here is what I would check in your case :


--> is the bt module from chihiros placed next to interferencing stuff?

--> do you use the internal antenna of the esp or external (stick on type works better for me compared to screw on with adapter cable)

--> what firmware is your light on?

--> do you have more then 3 ble light / devices? If so get another bt proxy installed :)


Hope that helps

________________________________
From: HannibalChau ***@***.***>
Sent: Friday, August 30, 2024 7:49:56 AM
To: TheMicDiet/chihiros-led-control ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheMicDiet/chihiros-led-control] Unable to add WRGB 2 10th edition (Issue #38)


Hello,

I'm having an issue adding WRGB 2 10th edition. Would you be able to add it? Device id: DYNW12PD9EC8584B299

Thanks

**Comment by TheMicDiet** [comment]
Hi @HannibalChau, is this the 120 cm version?

**Comment by HannibalChau** [comment]
Yes, firmware 22.

**Comment by HannibalChau** [comment]
That worked, thank you for the quick response. Now I just need to figure out an automation to do.  :)

**Comment by senna1992** [comment]
Claude and chatgpt.com are very helpful for that

________________________________
