### ISSUE TITLE
Working Vivid II

### ISSUE THREAD

**Issue by heraktitus** [TheMicDiet/chihiros-led-control#6]
Great Work Thnks, 
Will work on Integration on my Aqua Automation
It can work with HA probably with shell commands 
Also it needs to pull Auto and Manual mode data from the lamp. 
Also  with Python 3.11.2 working on Raspberry gives runtime error 
 typer.Option() missing 1 required positional argument: 'default' 

Working with Chihiros RGB VIVID II  witout much problem (needed to edit a code a little bit for Python, typer 0.7 version )
https://www.chihirosaquaticstudio.com/products/chihiros-rgb-vivid-ii-10-th-edition-18-built-in-bluetooth

**Comment by TheMicDiet** [comment]
Glad to hear. I don't think it is possible to pull the current auto or manual setting from the LED, you would have to store the current state by yourself.  

Is there a specific reason for you to not use the latest version of typer?
