### ISSUE TITLE
Python Flask on a Raspberry Pi Zero W = HA integration (Almost)

### ISSUE THREAD

**Issue by kdtt87** [TheMicDiet/chihiros-led-control#7]
First of all:
NICE WORK!

I was hoping for a HA integration. Meanwhile I took matters into my own hands by creating a small web server using Python Flask on a Raspberry Pi Zero W. I then use Node-RED to send a POST request to the Pi, containing RGB values, allowing me to control my WRGB II SLIM from Home Assistant.

Thank you for making this possible!

EDIT: Sorry for creating an issue - Couldn't find any other way to get in touch.

**Comment by TheMicDiet** [comment]
Hi, glad to hear that you've managed to build your own HA control.  I had planned to build a HA integration, but I didn't have the time to do it.

**Comment by kdtt87** [comment]
Do you plan to do it eventually or is the plan scrapped completely?

**Comment by TheMicDiet** [comment]
yes, I will probably do it.
