### ISSUE TITLE
How to connect to the module from PC?

### ISSUE THREAD

**Issue by cybericius** [TheMicDiet/chihiros-led-control#8]
Hi,
I have a Chihiros WRGBII module. When I want to add it through Bluetooth, discovery doesn't see it on PC (neither on Linux or Windows). Tried it while the phone was off, where connection works through the official app. 
Should I reset it in some ways? 
Thanks.

**Comment by cybericius** [comment]
(venv) akos@xray:~/python/chihiros-led-control$ python3 ./chihirosctl.py list-devices
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/akos/python/chihiros-led-control/./chihirosctl.py:25 in list_devices                       │
│                                                                                                  │
│    22 @app.command()                                                                             │
│    23 def list_devices(timeout: Annotated[int, typer.Option()] = 5):                             │
│    24 │   table = Table("Name", "Address")                                                       │
│ ❱  25 │   discovered_devices = asyncio.run(BleakScanner.discover(timeout))                       │
│    26 │   for device in discovered_devices:                                                      │
│    27 │   │   table.add_row(device.name, device.address)                                         │
│    28 │   print("Discovered the following devices:")                                             │
│                                                                                                  │
│ ╭─────────────────────── locals ────────────────────────╮                                        │
│ │   table = <rich.table.Table object at 0x7fa7254da9b0> │                                        │
│ │ timeout = 5                                           │                                        │
│ ╰───────────────────────────────────────────────────────╯                                        │
│                                                                                                  │
│ /usr/lib/python3.10/asyncio/runners.py:44 in run                                                 │
│                                                                                                  │
│   41 │   │   events.set_event_loop(loop)                                                         │
│   42 │   │   if debug is not None:                                                               │
│   43 │   │   │   loop.set_debug(debug)                                                           │
│ ❱ 44 │   │   return loop.run_until_complete(main)                                                │
│   45 │   finally:                                                                                │
│   46 │   │   try:                                                                                │
│   47 │   │   │   _cancel_all_tasks(loop)                                                         │
│                                                                                                  │
│ ╭──────────────────────────────── locals ────────────────────────────────╮                       │
│ │ debug = None                                                           │                       │
│ │  loop = <_UnixSelectorEventLoop running=False closed=True debug=False> │                       │
│ │  main = <coroutine object BleakScanner.discover at 0x7fa7255ffbc0>     │                       │
│ ╰────────────────────────────────────────────────────────────────────────╯                       │
│                                                                                                  │
│ /usr/lib/python3.10/asyncio/base_events.py:649 in run_until_complete                             │
│                                                                                                  │
│    646 │   │   if not future.done():                                                             │
│    647 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    648 │   │                                                                                     │
│ ❱  649 │   │   return future.result()                                                            │
│    650 │                                                                                         │
│    651 │   def stop(self):                                                                       │
│    652 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<BleakScanner.discover() done, defined at       │ │
│ │            /home/akos/python/chihiros-led-control/venv/lib/python3.10/site-packages/bleak/_… │ │
│ │            exception=BleakDBusError('org.bluez.Error.InProgress', 'Operation already in      │ │
│ │            progress')>                                                                       │ │
│ │ new_task = True                                                                              │ │
│ │     self = <_UnixSelectorEventLoop running=False closed=True debug=False>                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/akos/python/chihiros-led-control/venv/lib/python3.10/site-packages/bleak/__init__.py:242   │
│ in discover                                                                                      │
│                                                                                                  │
│   239 │   │   .. versionchanged:: 0.19.0                                                         │
│   240 │   │   │   Added ``return_adv`` parameter.                                                │
│   241 │   │   """                                                                                │
│ ❱ 242 │   │   async with cls(**kwargs) as scanner:                                               │
│   243 │   │   │   await asyncio.sleep(timeout)                                                   │
│   244 │   │                                                                                      │
│   245 │   │   if return_adv:                                                                     │
│                                                                                                  │
│ ╭────────────────────────── locals ──────────────────────────╮                                   │
│ │        cls = <class 'bleak.BleakScanner'>                  │                                   │
│ │     kwargs = {}                                            │                                   │
│ │ return_adv = False                                         │                                   │
│ │    scanner = <bleak.BleakScanner object at 0x7fa7254dae30> │                                   │
│ │    timeout = 5                                             │                                   │
│ ╰────────────────────────────────────────────────────────────╯                                   │
│                                                                                                  │
│ /home/akos/python/chihiros-led-control/venv/lib/python3.10/site-packages/bleak/__init__.py:156   │
│ in __aexit__                                                                                     │
│                                                                                                  │
│   153 │   │   return self                                                                        │
│   154 │                                                                                          │
│   155 │   async def __aexit__(self, exc_type, exc_val, exc_tb):                                  │
│ ❱ 156 │   │   await self._backend.stop()                                                         │
│   157 │                                                                                          │
│   158 │   def register_detection_callback(                                                       │
│   159 │   │   self, callback: Optional[AdvertisementDataCallback]                                │
│                                                                                                  │
│ ╭───────────────────────── locals ─────────────────────────╮                                     │
│ │   exc_tb = None                                          │                                     │
│ │ exc_type = None                                          │                                     │
│ │  exc_val = None                                          │                                     │
│ │     self = <bleak.BleakScanner object at 0x7fa7254dae30> │                                     │
│ ╰──────────────────────────────────────────────────────────╯                                     │
│                                                                                                  │
│ /home/akos/python/chihiros-led-control/venv/lib/python3.10/site-packages/bleak/backends/bluezdbu │
│ s/scanner.py:203 in stop                                                                         │
│                                                                                                  │
│   200 │   │   │   # avoid reentrancy                                                             │
│   201 │   │   │   stop, self._stop = self._stop, None                                            │
│   202 │   │   │                                                                                  │
│ ❱ 203 │   │   │   await stop()                                                                   │
│   204 │                                                                                          │
│   205 │   def set_scanning_filter(self, **kwargs) -> None:                                       │
│   206 │   │   """Sets OS level scanning filters for the BleakScanner.                            │
│                                                                                                  │
│ ╭───────────────────────────────────────── locals ─────────────────────────────────────────╮     │
│ │ self = <bleak.backends.bluezdbus.scanner.BleakScannerBlueZDBus object at 0x7fa7254db160> │     │
│ │ stop = <function BlueZManager.active_scan.<locals>.stop at 0x7fa7254e6440>               │     │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────╯     │
│                                                                                                  │
│ /home/akos/python/chihiros-led-control/venv/lib/python3.10/site-packages/bleak/backends/bluezdbu │
│ s/manager.py:390 in stop                                                                         │
│                                                                                                  │
│   387 │   │   │   │   │   │   )                                                                  │
│   388 │   │   │   │   │   │                                                                      │
│   389 │   │   │   │   │   │   try:                                                               │
│ ❱ 390 │   │   │   │   │   │   │   assert_reply(reply)                                            │
│   391 │   │   │   │   │   │   except BleakDBusError as ex:                                       │
│   392 │   │   │   │   │   │   │   if ex.dbus_error != "org.bluez.Error.NotReady":                │
│   393 │   │   │   │   │   │   │   │   raise                                                      │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                      adapter_path = '/org/bluez/hci0'                                        │ │
│ │                callback_and_state = CallbackAndState(                                        │ │
│ │                                     │   callback=<bound method                               │ │
│ │                                     BleakScannerBlueZDBus._handle_advertising_data of        │ │
│ │                                     <bleak.backends.bluezdbus.scanner.BleakScannerBlueZDBus  │ │
│ │                                     object at 0x7fa7254db160>>,                              │ │
│ │                                     │   adapter_path='/org/bluez/hci0'                       │ │
│ │                                     )                                                        │ │
│ │ device_removed_callback_and_state = DeviceRemovedCallbackAndState(                           │ │
│ │                                     │   callback=<bound method                               │ │
│ │                                     BleakScannerBlueZDBus._handle_device_removed of          │ │
│ │                                     <bleak.backends.bluezdbus.scanner.BleakScannerBlueZDBus  │ │
│ │                                     object at 0x7fa7254db160>>,                              │ │
│ │                                     │   adapter_path='/org/bluez/hci0'                       │ │
│ │                                     )                                                        │ │
│ │                             reply = <Message ERROR serial=358 reply_serial=8 sender=:1.9     │ │
│ │                                     destination=:1.182212 path=None interface=None           │ │
│ │                                     member=None error_name=org.bluez.Error.InProgress        │ │
│ │                                     signature=s body=['Operation already in progress']>      │ │
│ │                              self = <bleak.backends.bluezdbus.manager.BlueZManager object at │ │
│ │                                     0x7fa7254db1f0>                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/akos/python/chihiros-led-control/venv/lib/python3.10/site-packages/bleak/backends/bluezdbu │
│ s/utils.py:22 in assert_reply                                                                    │
│                                                                                                  │
│   19 │   │   AssertionError: if the message type is not ``MessageType.METHOD_RETURN``            │
│   20 │   """                                                                                     │
│   21 │   if reply.message_type == MessageType.ERROR:                                             │
│ ❱ 22 │   │   raise BleakDBusError(reply.error_name, reply.body)                                  │
│   23 │   assert reply.message_type == MessageType.METHOD_RETURN                                  │
│   24                                                                                             │
│   25                                                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ reply = <Message ERROR serial=358 reply_serial=8 sender=:1.9 destination=:1.182212 path=None │ │
│ │         interface=None member=None error_name=org.bluez.Error.InProgress signature=s         │ │
│ │         body=['Operation already in progress']>                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress

**Comment by TheMicDiet** [comment]
Hi, maybe your Bluetooth adapter is not compatible. However, you can try to delete the Chihiros device in the app and restart your PC to resolve this operation already in progress error.
